### ISSUE TITLE
New icons for Streets v7 launch

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/maki-2#13]
We need the following icons. Please assign yourself an icon if you are drawing it. @samanpwbb has offered to draw all the unassigned icons :)

- [x] `aquarium` https://github.com/mapbox/maki-2/issues/3 @karenzshea 
- [x] `bicycle-share` https://github.com/mapbox/maki-2/issues/14 @nickidlugash
- [x] `castle` https://github.com/mapbox/maki-2/issues/9 @nickidlugash
- [x] `doctor` (stethoscope) https://github.com/mapbox/maki-2/issues/18 @samanpwbb
- [x] `drinking-water` https://github.com/mapbox/maki-2/issues/10 @TheMarex 
- [x] `information` https://github.com/mapbox/maki-2/issues/5 @samanpwbb
- [x] `stadium` https://github.com/mapbox/maki-2/issues/2 @samanpwbb
- [x] `amusement-park` (ferris wheel?) https://github.com/mapbox/maki-2/issues/8 @samanpwbb 
- [x] `toilet` https://github.com/mapbox/maki-2/issues/15 @mayagao
- [x] `vet` (dog paw) https://github.com/mapbox/maki-2/issues/16 @mayagao
- [x] `attraction` (camera) https://github.com/mapbox/maki-2/issues/17 @samanpwbb
- [x] `mountain` (can be same or similar to `triangle`) https://github.com/mapbox/maki-2/issues/25
- [x] `volcano`

/cc @ajashton @amyleew

**Comment by samanpwbb** [comment]
We did this.
